cetav-ddw/cetav-2015

sites/all/themes/cetaviano/css/main.css, sites/all/themes/cetaviano/sass/main.scss, sites/all/themes/cetaviano/sass/partials/base/_base.scss, sites/all/themes/cetaviano/sass/partials/base/_headings.scss, sites/all/themes/cetaviano/sass/partials/base/_type.scss, sites/all/themes/cetaviano/sass/partials/patterns/_buttons.scss, sites/all/themes/cetaviano/sass/partials/patterns/_links.scss, sites/all/themes/cetaviano/sass/partials/patterns/_multi-media.scss, sites/all/themes/cetaviano/sass/partials/patterns/_tables.scss, sites/all/themes/cetaviano/sass/partials/patterns/forms/_forms-drupal.scss, sites/all/themes/cetaviano/sass/partials/patterns/forms/_forms.scss, sites/all/themes/cetaviano/sass/partials/utils/_mixins.scss, sites/all/themes/cetaviano/sass/partials/utils/_variables.scss
=> Add base styles

sites/all/themes/cetaviano/css/main.css, sites/all/themes/cetaviano/sass/main.scss, sites/all/themes/cetaviano/sass/partials/components/_preview-course.scss
=> Preview course

sites/all/themes/cetaviano/sass/partials/base/_base.scss, sites/all/themes/cetaviano/sass/partials/components/_news.scss, sites/all/themes/cetaviano/sass/partials/patterns/_links.scss
- Se hizo un cambios en news una clase general para que todos los links tengan un mismo tamaño 
- En la hoja de estilo base se agrego una regla general para los elementos con clase title
=> News links

sites/all/themes/cetaviano/sass/partials/patterns/_cetav-icons.scss
Ya lo de los iconos esta listo. Se cambió el tamaño de los iconos por que estaban muy grandes. Falta solo que fabián agregue las clases en el drupal para verlo en la página.
=> cambios en tamaño de iconos

sites/all/themes/cetaviano/sass/partials/components/_home-techs-intro.scss, sites/all/themes/cetaviano/sass/partials/layout/_layout.scss, sites/all/themes/cetaviano/sass/partials/patterns/_list.scss
Cambios en lista de carreras que sale en institución y cambio de paddings entre secciones.
=> Fixed padding in sections and list in cetav

sites/all/themes/cetaviano/Gruntfile.js
The sourcemaps for sass in the Gruntfile weren't working.
=> Gruntfile sourcemaps fixed

sites/all/themes/cetaviano/sass/partials/components/_graduate-profile.scss
I removed class that was applied in order to display none to panel titles.
**Note:**
It is necessary to add display none to title to the CTA region in Carreras in panel config on dev pantheon
=> Titles display none fixed

sites/all/themes/cetaviano/sass/partials/base/_headings.scss, sites/all/themes/cetaviano/sass/partials/layout/_layout.scss, sites/all/themes/cetaviano/sass/partials/utils/_variables.scss
Creating and updating standart styles like headings and spaces in the layout.
=> F029_creating_standart_styles

sites/all/themes/cetaviano/layouts/cetav_nodo-noticia/cetav-nodo-noticia.tpl.php, sites/all/themes/cetaviano/sass/partials/components/_news-node.scss, sites/all/themes/cetaviano/sass/partials/utils/_variables.scss
Imagestyles
Dates styles
Categories styles
Title styles
Img description styles
=> F006_new-node-styles

sites/all/themes/cetaviano/Gruntfile.js
=> B003_deleting_grunt_reload

sites/all/themes/cetaviano/sass/main.scss, sites/all/themes/cetaviano/sass/partials/components/_graduetes-reel.scss, sites/all/themes/cetaviano/sass/partials/patterns/_modals.scss
=> F036 fixed modal styles

sites/all/themes/cetaviano/sass/partials/components/_home-techs-intro.scss
=> fixing-responsive-carrers

sites/all/themes/cetaviano/sass/partials/patterns/_buttons.scss
Changing the font size of the buttons of categories
=> F038 changing category fontsize

sites/all/themes/cetaviano/sass/partials/components/_generations.scss, sites/all/themes/cetaviano/sass/partials/patterns/_buttons.scss
Graduetes generation styles and config
=> F019_graduetes-generations-view

sites/all/themes/cetaviano/sass/partials/patterns/_buttons.scss
Changing btn of view graduetes
=> F043_graduetes-generations-view-btn

sites/all/themes/cetaviano/sass/partials/patterns/_buttons.scss
Fixed the styles for the btn of news
=> F044_news-view-btn

sites/all/themes/cetaviano/sass/partials/components/_admission.scss
Fixing extra margin on admission
=> F045_fixing-admission-margin

sites/all/themes/cetaviano/sass/partials/layout/_layout.scss
Fixed bug in grid employers list
=> Fixed bug in grid employers list

sites/all/themes/cetaviano/sass/partials/components/_preview-graduates.scss
Changing graduetes view to the normal filters
=> F048_graduetes-generations-view-filter

sites/all/themes/cetaviano/sass/partials/components/_brand-components.scss
=> F049_fix-logos-home

sites/all/themes/cetaviano/sass/partials/components/_home-techs-intro.scss
Already works on firefox desktop and mobile.
=> F053_fixing-home-careers-firefox

sites/all/themes/cetaviano/sass/partials/patterns/_cetav-icons.scss
Adding color to portfolio icon, needed to Graduetes view
=> F053_graduetes-view-portfolio-icon

sites/all/themes/cetaviano/sass/partials/components/_home-hero.scss
Correction position of bg hero, now woks on small devices.
=> F054 fixing img hero

sites/all/themes/cetaviano/sass/partials/patterns/_modals.scss
Deleted opacity on small devices
=> Deleted opacity on small devices

sites/all/themes/cetaviano/layouts/cetav_egresados/cetav-egresados.tpl.php
Adding slab-gray class to generations section on cetav-egresados.tpl
=> F055_add-generations-view-color

sites/all/themes/cetaviano/sass/partials/components/_preview-graduates.scss
Adding extra space to section wide graduates to validate the principle of proximity with the view of graduates
=> F056_fixing-section-wide-egresados-spacing

sites/all/themes/cetaviano/layouts/cetav_empleabilidad/cetav-empleabilidad.tpl.php, sites/all/themes/cetaviano/sass/partials/components/_preview-graduates.scss, sites/all/themes/cetaviano/sass/partials/layout/_layout.scss
Update the layout and remove space between graphics and previous section
=> F049_fixing-employability-spacing

sites/all/themes/cetaviano/sass/partials/components/_videos-workshops.scss, sites/all/themes/cetaviano/sass/partials/layout/_layout.scss, sites/all/themes/cetaviano/sass/partials/patterns/_titles.scss
=> F046_employability-config

sites/all/themes/cetaviano/sass/partials/base/_type.scss, sites/all/themes/cetaviano/sass/partials/components/_home-hero.scss, sites/all/themes/cetaviano/sass/partials/components/_navigation.scss, sites/all/themes/cetaviano/sass/partials/patterns/_titles.scss
Styles for the title of the taxonomy page added
=> F059_taxonomy-news-title

sites/all/themes/cetaviano/layouts/cetav_frontpage/cetav-frontpage.tpl.php
Changing frontpage sections color.
=> F062_fixing-layout-home

sites/all/themes/cetaviano/sass/partials/patterns/_modals.scss
Added new class for container modal
=> Added new class for container modal

sites/all/themes/cetaviano/layouts/cetav_empleabilidad/cetav-empleabilidad.tpl.php, sites/all/themes/cetaviano/sass/main.scss
-Imported videos-workshops
-Added styles on employability tpl
=> F067 employability import workshops

sites/all/themes/cetaviano/sass/partials/components/_home-techs-intro.scss
*Laura asked aligment the botons inside home careers.
=> F058 careers btn aligment

sites/all/themes/cetaviano/layouts/cetav_empleabilidad/cetav-empleabilidad.tpl.php
Changed the position of the style
=> Add tpl style

sites/all/themes/cetaviano/sass/partials/components/_preview-graduates.scss
=> Image styles: graduates

sites/all/themes/cetaviano/layouts/cetav_perfil-egresado/cetav-perfil-egresado.tpl.php, sites/all/themes/cetaviano/layouts/cetav_perfil-egresado/cetav_perfil-egresado.inc, sites/all/themes/cetaviano/sass/partials/components/_graduate-profile.scss
Cleaning graduetes profile css and tpl
=> F072_clean-graduates-profile-css

sites/all/themes/cetaviano/sass/partials/components/_generations.scss, sites/all/themes/cetaviano/sass/partials/patterns/_modals.scss
Modified generations classes in order to add modal
=> F032 modal graduetes yearbook

sites/all/themes/cetaviano/sass/partials/components/_navigation-footer.scss
Adjust back to top in mobile devices
=> F073 fixing back to top mobile

sites/all/themes/cetaviano/sass/partials/components/_hero-images.scss, sites/all/themes/cetaviano/sass/partials/layout/_layout.scss
Implementing media query to title position
Erasing max-height: 350px
=> F070 call out heading improvements

sites/all/themes/cetaviano/sass/partials/components/_one-pager.scss
=> F075_change-titles-one-pager

sites/all/themes/cetaviano/sass/partials/components/_videos-workshops.scss, sites/all/themes/cetaviano/sass/partials/third-party/system/_system.scss
=> Align videos

sites/all/themes/cetaviano/sass/partials/components/_careers.scss
=> F085_change-layout-skill-carrers

sites/all/themes/cetaviano/sass/partials/components/_home-techs-intro.scss, sites/all/themes/cetaviano/templates/views/views-view-fields--carreras-home.tpl.php
Bug fixed
Relationship between tlp and career names
=> F076 fix template home carrers

robots.txt
Modifying the file robots.txt to allow the markup of twitter cards
=> F086_modifying-robots.txt

sites/all/themes/cetaviano/template.php
Killing livereload from template.php
=> Killing livereload

sites/all/themes/cetaviano/sass/partials/components/_team-node.scss
Remove max-width on team member full content
=> Remove max-width on team member full content

sites/all/themes/cetaviano/src-js/graph.js
Fixing graphic, deleting the symbol with id and the svg use attribute
=> B006_fixing-empleability-graphics

sites/all/themes/cetaviano/layouts/cetav_admision/cetav-admision.tpl.php, sites/all/themes/cetaviano/sass/version2/pages/_carreer.scss, sites/all/themes/cetaviano/sass/version2/partials/_admision.scss
Se corrigieron los estilos en los que habían problemas en el sitio de pruebas, también se cambió la variable de los títulos de las secciones de cada carrera, para que los títulos del sitio sean iguales.
=> Corrección de estilos en sección de admisiones

sites/all/themes/cetaviano/sass/partials/components/_preview-graduates.scss
.views-exposed-form .form-item {
// margin-bottom: 12px;
}
=> Cambios en margin de filtro en sección de egresados
